version: '3.8'

services:
  app:
    container_name: finance-app-dev
    image: helion444/finance_webapp_dev:v1
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    restart: unless-stopped
    networks:
      - finance

networks:
  finance:
    driver: bridge
