apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-webapp-config-qa
  namespace: financial-app-k8s
  labels:
    app: finance-webapp
    environment: qa
data:
  ENV: "qa"
  LOG_LEVEL: "INFO"
  FEATURE_FLAG_NEW_UI: "false"
  APP_PORT: "5000"
  APP_HOST: "0.0.0.0"