# Python 3.10 slim image because the app is running on version 3.10.14
FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 5000

CMD ["flask", "run"]